### ISSUE TITLE
Run tslint and fix all violations

### ISSUE THREAD

**Issue by ppitonak** [fabric8io/fabric8-test#470]
- Optionally, enforce linting during build on CI
- Remove all ` tslint:disable-next-line:max-line-length`

**Comment by ppitonak** [comment]
* [ ] upgrade tslint PR #800
* [ ] sort configuration file alphabetically PR #800
* [ ] fix rules violations PR #800
* [ ] introduce rule https://palantir.github.io/tslint/rules/no-unused-variable/
* [ ] introduce rule https://palantir.github.io/tslint/rules/no-duplicate-imports/
* [ ] introduce rule https://palantir.github.io/tslint/rules/no-consecutive-blank-lines/
* [ ] introduce rule https://palantir.github.io/tslint/rules/ordered-imports/
* [ ] discuss introduction of new rules listed below

To discuss:
* https://palantir.github.io/tslint/rules/no-any/
* https://palantir.github.io/tslint/rules/only-arrow-functions/
* https://palantir.github.io/tslint/rules/prefer-for-of/
* https://palantir.github.io/tslint/rules/promise-function-async/
* https://palantir.github.io/tslint/rules/typedef/
* https://palantir.github.io/tslint/rules/await-promise/
* https://palantir.github.io/tslint/rules/no-console/
* https://palantir.github.io/tslint/rules/no-empty/
* https://palantir.github.io/tslint/rules/no-floating-promises/
* https://palantir.github.io/tslint/rules/no-implicit-dependencies/
* https://palantir.github.io/tslint/rules/no-inferred-empty-object-type/
* https://palantir.github.io/tslint/rules/no-return-await/
* https://palantir.github.io/tslint/rules/no-sparse-arrays/
* https://palantir.github.io/tslint/rules/no-null-keyword/
* https://palantir.github.io/tslint/rules/no-unsafe-finally/
* https://palantir.github.io/tslint/rules/prefer-conditional-expression/
* https://palantir.github.io/tslint/rules/deprecation/
* https://palantir.github.io/tslint/rules/prefer-const/

**Comment by ppitonak** [comment]
The remaining tasks will be solved in #837 and #838
