### ISSUE TITLE
Expand BDD/API Booster test POC into test suite

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-test#782]
* [x] #793 Add routes for stage and run to test
* [x] #785 Add support for promoting build from stage to run
* [x] #799 Add error handling to tests and supporting code
* [ ] #798 Parameterize pass and fail handling to support all boosters and OSIO quickstarts
* [ ] #797 Add negative tests
* [ ] #794 Configure test suite to run against blank booster daily on Centos CI
  * [ ] Measure response time of the API calls and track it in Zabbix
* [ ] #796 Configure tests to run on all pull requests to OSIO quickstarts
* [x] #795 Add reporting finer than overall pass/fail

https://openshift.io/openshiftio/openshiftio/plan/detail/2616

**Comment by pmacik** [comment]
Obsolete, closing.
